name: 'ci_build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v3
        id: create_check_run
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const url = `POST /repos/:repository/check-runs`;
            var result = await github.request(url, {
              name: 'Tests',
              head_sha: '${{ github.sha }}',
              repository: process.env.GITHUB_REPOSITORY
            });
            return result.data.id;

      - run: echo "$DUMP"
        env:
          DUMP: ${{ toJSON(steps.create_check_run.outputs) }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const url = `POST /repos/${process.env.GITHUB_REPOSITORY}/actions/workflows/test-test.yml/dispatches`;
            github.request(url, {
              ref: process.env.GITHUB_REF,
              inputs: {
                parent_run_number: process.env.GITHUB_RUN_NUMBER,
                test_check_run_id: process.env.TEST_CHECK_RUN_ID
              }
            });
        env:
          TEST_CHECK_RUN_ID: ${{ steps.create_check_run.outputs.result }}
