name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PATH=/usr/local/libexec/sccache:/usr/local/bin:$PATH" >> "$GITHUB_ENV"
          echo "SCCACHE_ERROR_LOG=$(pwd)/sccache.log" >> "$GITHUB_ENV"
          echo "SCCACHE_LOG=sccache=trace" >> "$GITHUB_ENV"
          set -x

          wget --output-document sccache.tar.gz "https://github.com/mozilla/sccache/releases/download/v0.8.1/sccache-v0.8.1-$ARCH_AND_OS.tar.gz"
          tar xzf sccache.tar.gz
          rm sccache.tar.gz
          sudo mv sccache*/sccache /usr/local/bin/sccache
          rm -rf sccache*

          sudo mkdir -p /usr/local/libexec/sccache
          for PROG in cc c++; do
            FULLPATH=$(command -v "$PROG")
            echo '#!/bin/sh' > "$PROG"
            echo "exec /usr/local/bin/sccache $FULLPATH \"\$@\"" >> "$PROG"
            cat "$PROG"
            chmod +x "$PROG"
            sudo mv "$PROG" /usr/local/libexec/sccache/
          done

          touch sccache.log
          env SCCACHE_START_SERVER=1 sccache
        env:
          ARCH_AND_OS: x86_64-unknown-linux-musl
      - run: echo > test.c
      - run: cc -c test.c
      - run: |
          sccache --stop-server
          cat sccache.log

      #- run: sudo apt update
      #- run: sudo apt install -y libcurl4-openssl-dev
