name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: mkdir foo/bar
      - run: touch foo/bar/baz.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: foo/bar/**/*
