name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - name: GCloud login
        run: |
          echo "$GCLOUD_KEY" > gcloud.json
          gcloud auth activate-service-account --key-file gcloud.json
        shell: bash
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      - name: Set Google Cloud project
        run: gcloud config set core/project fullstaq-ruby
      - run: gcloud secrets versions access latest --secret gpg-private-key >/dev/null
