name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: sudo env PATH="$PATH" ruby -v
      - run: sudo -E ruby -v
