name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: get-id-token
        with:
          script: |
            fs.writeFileSync(process.env.GITHUB_OUTPUT,
              'id_token=' + await core.getIDToken('https://backend.fullstaqruby.org'),
              { mode: 'a' })
      - run: |
          curl -X POST -H "Authorization: Bearer $TOKEN" -v "https://apt.fullstaqruby.org/admin/upgrade_apiserver"
        env:
          TOKEN: ${{ steps.get-id-token.outputs.id_token }}
