name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          set -e

          ARCH=aarch64-apple-darwin

          echo "PATH=/usr/local/libexec/sccache:$PATH" >> "$GITHUB_ENV"
          echo "SCCACHE_ERROR_LOG=$(tty)" >> "$GITHUB_ENV"

          set -x

          wget --output-document sccache.tar.gz "https://github.com/mozilla/sccache/releases/download/v0.8.1/sccache-v0.8.1-$ARCH.tar.gz"
          tar xzf sccache.tar.gz
          rm sccache.tar.gz
          sudo mv sccache* /usr/local/bin/sccache

          mkdir -p /opt/sccache
          sudo ln -s /usr/local/bin/sccache /opt/sccache/cc
          sudo ln -s /usr/local/bin/sccache /opt/sccache/c++

          SCCACHE_START_SERVER=1 sccache

      #- run: sudo apt update
      #- run: sudo apt install -y libcurl4-openssl-dev
      - run: echo '#include <curl/curl.h>' > test.cpp
      - run: set -o pipefail && c++ -c test.cpp -v | head -n 100
