name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: windows-2019
    steps:
      - run: |
          false
          true
      - run: 'false'
      - run: |
          $ErrorActionPreference = 'Stop'
          false
          true
