name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
  
  sub1:
    strategy:
      matrix:
        name: ['1', '2']
    uses: "./.github/workflows/sub-${{ matrix.name }}.yml"
