name: 'CI: build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/:repository/check-runs
          repository: ${{ github.repository }}
          mediaType: | # The | is significant!
            previews: 
              - antiope
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: octokit/request-action@v2.x
      #   id: update_check_run
      #   with:
      #     route: PATCH /repos/:repository/check-runs/:check_run_id
      #     repository: ${{ github.repository }}
      #     mediaType: | # The | is significant!
      #       previews: 
      #         - antiope
      #     check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
      #     conclusion: "success"
      #     status: "completed"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          debug: true
          script: |
            const url = `POST /repos/${process.env.GITHUB_REPOSITORY}/actions/workflows/test-test.yml/dispatches`;
            return await github.request(url, { ref: process.env.GITHUB_REF });
