name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: sudo ruby -e "$SCRIPT"
        env:
          SCRIPT: |
            File.open("/tmp/foo.c", "w").close
            output = `cc '/tmp/foo.c' -c -o '/tmp/foo.o' 2>&1`
            p $?
            puts "----"
            puts output
            puts "----"
