name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    if: false
    steps:
      - run: true

  bar:
    runs-on: ubuntu-20.04
    steps:
      - run: true

  baz:
    needs:
      - foo
      - bar
    runs-on: ubuntu-20.04
    steps:
      - run: true
