name: 'CI: build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const url = `POST /repos/${process.env.GITHUB_REPOSITORY}/check-runs`;
            github.request(url, {
              name: 'Tests',
              head_sha: '${{ github.sha }}'
            });

      # - uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       const url = `POST /repos/${process.env.GITHUB_REPOSITORY}/actions/workflows/test-test.yml/dispatches`;
      #       github.request(url, { ref: process.env.GITHUB_REF });
