name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo $TMPDIR
      - run: sudo sh -c 'echo $TMPDIR'
      - run: sudo -E sh -c 'echo hi > $TMPDIR/test.txt && cat $TMPDIR/test.txt'
