name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: windows-2019
    steps:
      - run: |
          false
          true
          false
      
      # succeeds
      # - run: |
      #     false
      #     true

      # fails
      #- run: 'false'
      
      - run: |
          $ErrorActionPreference = 'Stop'
          false
          true
