name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-14
    steps:
      - run: sudo sh -c "$SCRIPT"
        env:
          SCRIPT: |
            exec 2>&1  
            set -x
            mkdir /tmp/foo
            touch /tmp/foo/foo.c
            cc -c /tmp/foo/foo.c
