name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo '#include <curl/curl.h>' > test.c
      - run: cc -c test.c
      - run: cpp -v <<<'#include <curl/curl.h>' | head
