name: 'CI: build'

on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: 'true'

  trigger_test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/test-test/dispatches
          ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
