name: 'CI: build'

on:
  push: {}
  pull_request_target:
    types: [opened, synchronize]

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: false
        id: f
      - run: echo previous step failed
        if: failure() && steps.f.outcome == 'failure'
