name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    env:
      PRODUCT_VERSION: '0.9.0'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags

      - name: Determine changelog
        run: |
          MERGE_BASE=$(git merge-base origin/master HEAD)
          echo "Merge base: $MERGE_BASE"

          if PREVIOUS_RELEASE_TAG=$(git describe "$MERGE_BASE" --tags --abbrev=0 --match='v*' 2>/dev/null); then
            echo "Previous release: $PREVIOUS_RELEASE_TAG"
            git log --pretty='format:%s' "$PREVIOUS_RELEASE_TAG..HEAD" > changelog.txt
          else
            echo "No previous release found"
            git log --pretty='format:%s' > changelog.txt
          fi

          echo
          echo "## Changelog"
          cat changelog.txt

      - name: Create tag
        run: |
          set -x
          git tag "v${PRODUCT_VERSION}"
          git push origin "v${PRODUCT_VERSION}"

      - name: Create release
        run: gh release create "$v{PRODUCT_VERSION}" --draft --notes-file changelog.txt --title "Version $PRODUCT_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
