name: 'CI: build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/test-test/dispatches
          ref: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
