name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - name: GCloud login
        run: gcloud auth activate-service-account --key-file <(base64 -d <<< "$GCLOUD_KEY")
        shell: bash
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      - run: gcloud secrets versions access latest --secret gpg-private-key >/dev/null
