name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo '#include <openssl/err.h>' > test.cpp
      - run: brew install openssl@3
      - run: set -o pipefail && c++ -c test.cpp -v | head -n 100
