name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l --color -Fh
      - run: which ruby
      - run: ruby -v
      - run: echo $PATH
