name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: pwd
      - run: df -h
      - run: echo "$AGENT_TOOLSDIRECTORY"
      - run: du -chd 1 "$AGENT_TOOLSDIRECTORY"
      - run: |
          set -x
          sudo apt purge -y aria2 shellcheck rpm zsync google-chrome-stable
          sudo apt purge -y ant ant-optional kubectl mercurial apt-transport-https yarn libssl-dev
          sudo apt purge -y libfreetype6 libfreetype6-dev libfontconfig1 snmp pollinate libpq-dev sphinxsearch
          # sudo apt purge aria2 shellcheck rpm zsync google-chrome-stable \
          #   ant ant-optional kubectl mercurial apt-transport-https yarn libssl-dev \
          #   libfreetype6 libfreetype6-dev libfontconfig1 snmp pollinate libpq-dev sphinxsearch
          sudo apt purge -y '~n ^mysql'
          sudo apt purge -y '~n ^php'
          sudo apt purge -y '~n ^dotnet'
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" /usr/share/dotnet /usr/local/lib/android /opt/ghc \
              /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup /usr/lib/jvm
      - run: df -h
