name: 'CI: build'

on:
  workflow_dispatch: {}
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - run: apt update && apt install -y ansible
      - run: ansible --version
