name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: windows-2019
    steps:
      # fails
      # - run: |
      #     false
      #     true
      #     false
      
      # succeeds
      # - run: |
      #     false
      #     true

      # fails
      #- run: 'false'
      
      - run: |
          $ErrorActionPreference = 'Stop'
          Set-PSDebug -Trace 1
          /bin/false
          /bin/true
