name: 'CI: build'

on:
  workflow_dispatch: {}
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt update && sudo apt install -y ansible
      - run: ansible --version
