name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: ruby -v
      - run: sudo ruby -v
      - run: env | sort
      - run: sudo env PATH="$PATH" ruby -v