name: 'CI: build'

on:
  push: {}
  pull_request_target:
    types: [opened, synchronize]

jobs:
  foo:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: csrutil status
