name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - name: Set status
        run: echo '::set-output name=status::dit is mijn output tekst'
        id: combinestepstatus
      - name: echo
        run:
          echo ${{ steps.combinestepstatus.outputs.status}}
