name: 'ci_build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Create check for 'Build packages'
        uses: LouisBrunner/checks-action@v1.1.0
        id: create_check_build_packages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Build packages
          status: queued
          details_url: https://github.com/1234
          output: |
            {
              "summary": "Packages are being built in another workflow.\n[**➜ See workflow run #1234 for logs**](https://github.com/1234)"
            }
      - run: sleep 10
      - run: 'false'

  fail:
    runs-on: ubuntu-20.04
    if: failure()
    steps:
      - run: echo fail
