name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: windows-2019
    steps:
      # fails
      # - run: |
      #     false
      #     true
      #     false
      
      # succeeds
      # - run: |
      #     false
      #     true

      # fails
      #- run: 'false'
      
      - run: |
          docker x
          if ($LastExitCode -ne 0) {
            exit 1
          }
          docker --help
