name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: get-id-token
        with:
          script: |
            require('fs').writeFileSync(process.env.GITHUB_OUTPUT,
              'id_token<<EOF\n' + (await core.getIDToken('backend.fullstaqruby.org')) + '\nEOF\n',
              { flag: 'a' })
      - run: base64 <<<"$TOKEN"
        env:
          TOKEN: ${{ steps.get-id-token.outputs.id_token }}
