name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: passenger_website_test
          POSTGRES_USER: passenger_website_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - run: host postgres
