name: 'CI: build'

on:
  push: {}
  pull_request_target:
    types: [opened, synchronize]

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo v2
      - run: echo "$INPUT"
        env:
          INPUT: ${{ toJSON(github.event) }}
      - run: cat README.md
