name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: pwd
      - run: df -h
      - run: df -h .
      - run: >
          du -chd 1 /usr/share/dotnet /usr/local/lib/android /opt/ghc
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup
          /usr/lib/jvm
      - run: echo "$AGENT_TOOLSDIRECTORY"
      - run: du -chd 1 "$AGENT_TOOLSDIRECTORY"
      - run: find "$AGENT_TOOLSDIRECTORY" -maxdepth 2
      - run: ruby --version
