name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: pwd
      - run: df -h
      - run: df -h .
      - run: du -chd 1 /usr/share/dotnet
      - run: echo "$AGENT_TOOLSDIRECTORY"
      - run: du -chd 1 "$AGENT_TOOLSDIRECTORY"
      - run: find "$AGENT_TOOLSDIRECTORY" -maxdepth 2
