name: 'CI: build'

on:
  workflow_dispatch: {}
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  analyze:
    if: false
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
          - language: rust
    steps:
      - run: echo hello world

  codeql-final-verdict:
    name: Final verdict
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - run: 'true'
