name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo '#include <openssl/err.h>' > test.cpp
      - run: set -o pipefail && c++ -I/opt/homebrew/opt/openssl@3/include -c test.cpp -v | head -n 100
        #env:
        #  CFLAGS: /opt/homebrew/opt/openssl@3/include
