name: 'ci_build'

on:
  - push

jobs:
  trigger_test:
    runs-on: ubuntu-20.04
    steps:
      - run: sleep 10
      - run: 'false'

  fail:
    runs-on: ubuntu-20.04
    if: failure()
    steps:
      - run: echo fail
