name: 'CI: build'

on:
  push: {}

jobs:
  test:
    runs-on: macos-14
    steps:
      - run: echo "$CONFIG" > cert_config.cnf
        env:
          CONFIG: |
            [ req ]
            default_bits = 2048
            prompt = no
            default_md = sha256
            distinguished_name = req_distinguished_name
            req_extensions = req_ext

            [ req_distinguished_name ]
            CN = Developer

            [ req_ext ]
            keyUsage = critical, digitalSignature, keyEncipherment
            extendedKeyUsage = codeSigning

      - name: Private key and CSR
        run: openssl req -new -newkey rsa:2048 -nodes -keyout github-ci.key -out github-ci.csr -config cert_config.cnf

      - name: Certificate
        run: openssl x509 -req -in github-ci.csr -signkey github-ci.key -out github-ci.crt -days 3650 -extensions req_ext -extfile cert_config.cnf
      
      - name: P12
        run: openssl pkcs12 -export -out github-ci.p12 -inkey github-ci.key -in github-ci.crt -name "Github CI" -password "pass:"
      
      - name: Import
        run: sudo security add-trusted-cert -d -r trustRoot -k ~/Library/Keychains/login.keychain-db github-ci.p12
      
      - name: Compile
        run: echo 'int main() { return 0; }' > foo.c && cc foo.c -o foo
      
      - name: Sign
        run: codesign -s "Github CI" foo
