name: 'CI: build'

on:
  push: {}

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
