name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-18.04
    #if: 'false'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
        continue-on-error: true
      - run: echo hello && sleep 10
      - run: touch hello.txt
      - name: Archive artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: .
      - run: false

  job2:
    runs-on: ubuntu-18.04
    needs: job1
    # Run even if job1 has been skipped
    if: '!failure() && !cancelled()'
    steps:
      - id: dl
        uses: actions/download-artifact@v2
        with:
          name: foo
        continue-on-error: true
      - id: foo
        run: echo "::set-output name=action_fruit::strawberry"
      - run: echo '${{ toJSON(steps) }}'
      - run: echo '${{ toJSON(steps.foo) }}'
      - run: echo '${{ toJSON(steps.foo.outputs) }}'
