name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - name: dl
        uses: actions/download-artifact@v2
        with:
          name: foo
        continue-on-error: true
      - name: foo
        run: echo "::set-output name=action_fruit::strawberry"
      - run: echo ${{ toJSON(steps) }}
