name: CI/CD

on:
  - push

env:
  CI_NUM: ${{ github.run_number }}

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo hello world
      - run: echo CI_NUM=${{ env.CI_NUM }}
      - run: echo CI_NUM="$CI_NUM"
      - run: echo "::warning ::Missing semicolon"
