name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-20.04
    outputs:
      test: ${{ steps.test.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: test no clear
        id: test
        run: echo '::set-output name=matrix::{"foo":"bar","bool1":true,"bool2":false}'

  job2:
    runs-on: ubuntu-20.04
    needs: job1
    if: fromJSON(needs.job1.outputs.test).bool1
    steps:
      - run: echo done

  job3:
    runs-on: ubuntu-20.04
    needs: job1
    if: fromJSON(needs.job1.outputs.test).bool2
    steps:
      - run: echo done
