name: CI/CD

on:
  - push

jobs:
  job1:
    strategy:
      matrix:
        image:
          - name: image1
          - name: image2
    runs-on: ubuntu-18.04
    steps:
      - run: echo hello
    outputs:
      image-name: ${{ matrix.image.name }}

  job2:
    runs-on: ubuntu-18.04
    steps:
      - run: echo hello
    outputs:
      image-name: job2image

  job3:
    runs-on: ubuntu-18.04
    needs:
      - job1
      - job2
    steps:
      - run: echo job1-image-name=${{ needs.job1.outputs.image-name }}
      - run: echo job2-image-name=${{ needs.job2.outputs.image-name }}