name: CI/CD

on:
  - push

env:
  CI_NUM: ${{ github.run_number }}

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: test no clear
        uses: ./github/actions/test
      - name: test clear=true (boolean)
        uses: ./github/actions/test
        with:
          clear: true
      - name: test clear=true (string)
        uses: ./github/actions/test
        with:
          clear: 'true'
