name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - name: list binfmt
        run: ls -1 /proc/sys/fs/binfmt_misc | sort
      - name: arm32v7
        run: docker run --rm arm32v7/busybox uname -a
      - name: aarch64
        run: docker run --rm aarch64/busybox uname -a
