name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - name: list binfmt
        run: ls -1 /proc/sys/fs/binfmt_misc | sort
      - name: install qemu-user-static
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: arm32v7
        run: docker run --rm arm32v7/busybox uname -a
        continue-on-error: true
      - name: aarch64
        run: docker run --rm arm64v8/busybox uname -a
        continue-on-error: true
