name: CI/CD

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-18.04
    if: 'false'
    steps:
      - run: echo hello

  job2:
    runs-on: ubuntu-18.04
    needs: job1
    if: 'always()'
    steps:
      - id: dl
        uses: actions/download-artifact@v2
        with:
          name: foo
        continue-on-error: true
      - id: foo
        run: echo "::set-output name=action_fruit::strawberry"
      - run: echo '${{ toJSON(steps) }}'
      - run: echo '${{ toJSON(steps.foo) }}'
      - run: echo '${{ toJSON(steps.foo.outputs) }}'
