# A job is skipped if at least one dependency is skipped.

name: CI/CD

on:
  - push

jobs:
  a:
    runs-on: ubuntu-20.04
    if: 'false'
    steps:
      - run: 'true'

  b:
    runs-on: ubuntu-20.04
    steps:
      - run: 'true'

  c:
    runs-on: ubuntu-20.04
    needs:
      - a
      - b
    steps:
      - run: 'true'

  # determine_docker_container_needs_building:
  #   runs-on: ubuntu-20.04
  #   outputs:
  #     needed: 'false'
  #   steps:
  #     - run: 'true'

  # build_docker_container:
  #   runs-on: ubuntu-20.04
  #   needs:
  #     - determine_docker_container_needs_building
  #   if: needs.determine_docker_container_needs_building.outputs.needed == 'true'
  #   steps:
  #     - run: 'true'

  # build_app:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: 'false'

  # publish:
  #   runs-on: ubuntu-20.04
  #   needs:
  #     - build_docker_container
  #     - build_app
  #   if: '!failure() && !cancelled()'
  #   # Expectation:
  #   # Only run if:
  #   # (build_docker_container is successful or skipped)
  #   # AND
  #   # (build_app is successful)
  #   #
  #   # Not run if:
  #   # (build_app failed)
  #   # OR
  #   # (build_docker_container failed)
  #   steps:
  #     - run: 'true'

  # commit_publication:
  #   runs-on: ubuntu-20.04
  #   needs:
  #     - publish
  #   steps:
  #     - run: 'echo "$STATUS"'
  #       env:
  #         STATUS: ${{ toJSON(needs.publish) }}
  #     - run: 'false'
