name: CI/CD

on:
  - push

jobs:
  commit_published_packages_test:
    runs-on: ubuntu-20.04
    if: 'false'
    steps:
      - run: 'true'

  test_packages_against_test:
    runs-on: ubuntu-20.04
    needs:
      - commit_published_packages_test
    if: |
      true && !failure() && !cancelled()
    steps:
      - run: 'false'
