name: CI/CD

on:
  - push

env:
  CI_NUM: ${{ github.run_number }}
  MY_ENV1: foo

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: test no clear
        uses: ./.github/actions/test
      - name: test clear=true (boolean)
        uses: ./.github/actions/test
        with:
          clear: true
      - name: test clear=true (string)
        uses: ./.github/actions/test
        with:
          clear: 'true'
      - name: expect foo
        run: echo ${{ env.MY_ENV1 || github.run_number }}
      - name: expect run_number
        run: echo ${{ env.MY_ENV2 || github.run_number }}
