name: 'ci_test'

on:
  workflow_dispatch:
    inputs:
      parent_run_number:
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github.event) }}
