name: 'CI: test'

on:
  workflow_dispatch:
    inputs:
      parent_run_number:
        required: false
  workflow_run:
    workflows:
      - 'CI: build'
    #types:
    #  - completed

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github.event) }}
