name: 'ci_test'

on:
  workflow_dispatch:
    inputs:
      parent_run_number:
        required: false
      test_check_run_id:
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github.event) }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `PATCH /repos/:repository/check-runs/:id`;
            github.request(url, {
              repository: process.env.GITHUB_REPOSITORY,
              id: github.event.inputs.test_check_run_id,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Test successful',
                summary: `[See details](/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.GITHUB_RUN_ID})`
              }
            });
