name: 'ci_test'

on:
  workflow_dispatch:
    inputs:
      parent_run_number:
        required: false
      test_check_run_id:
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github.event) }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `PATCH /repos/:repository/check-runs`;
            github.request(url, {
              name: 'Tests',
              head_sha: '${{ github.sha }}',
              repository: process.env.GITHUB_REPOSITORY
            });
